language: c++
compiler:
  - clang
  - gcc
env:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="5" NWJS_VERSION="0.12.3"
os:
  - linux
  - osx
sudo: false
cache:
  - pip
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - echo "$TRAVIS_NODE_VERSION"
  - export "PATH=./node_modules/.bin:$PWD/node_modules/.bin:$HOME/.local/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_5d419efedfca_key -iv $encrypted_5d419efedfca_iv -in .travis.id_rsa.enc -out .travis.id_rsa -d
  - chmod 0600 .travis.id_rsa
  # dummy 7z because npm wants to run the prepublish script
  - mkdir -p $HOME/.local/bin/ && touch $HOME/.local/bin/7z && chmod +x $HOME/.local/bin/7z 
  # coveralls
  - pip install --user cpp-coveralls coveralls-merge
  # compilers
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; AR="gcc-ar-4.8"; RANLIB="gcc-ranlib-4.8"; NM="gcc-nm-4.8" LTO_FLAG="-flto"; fi
  - if [ "$CXX" = "clang++" ]; then export NPMOPT=--clang=1 LTO_FLAG=""; fi
  # node versions
  - rm -rf ~/.nvm
  - git clone --branch v0.30.2 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install "$TRAVIS_NODE_VERSION"
  - if [ -n "$NWJS_VERSION" ]; then export DISPLAY=:99.0 ; sh -e /etc/init.d/xvfb start || true ; sleep 3 ; fi
  - if [ -n "$NWJS_VERSION" ]; then npm install "nw@$NWJS_VERSION" "nw-gyp@$NWJS_VERSION"; export NPG_ARGS="--runtime=node-webkit --target=$NWJS_VERSION"; fi
  - node --version
  # no coverage for tags (they are release builds!)
  - if [ -z "$TRAVIS_TAG" ]; then export DO_COVERAGE=1; fi
  - if [ -n "$TRAVIS_TAG" ]; then export CFLAGS="$CFLAGS -O3 $LTO_FLAG" LDFLAGS="$LDFLAGS $LTO_FLAG"; fi
  - if [ -n "$DO_COVERAGE" ]; then export LDFLAGS="$LDFLAGS --coverage" CFLAGS="$CFLAGS --coverage"; fi
  - echo "CFLAGS=\"$CFLAGS\" LDFLAGS=\"$LDFLAGS\""
install:
  - npm install $NPMOPT --build-from-source $NPG_ARGS
script:
  - if [ -z "$NWJS_VERSION" ]; then node --expose-gc ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec -s 1000 -t 5000; fi
  - if [ -n "$NWJS_VERSION" ]; then (cd test/nwjs && nw && node exitcode.js); fi
  - npm run jshint
after_success:
  - if [ -n "$DO_COVERAGE" ]; then cpp-coveralls --gcov-options '\-lp' --build-root build --exclude build/liblzma --exclude node_modules --dump coverage/cppfiles.json; fi
  - if [ -n "$DO_COVERAGE" ]; then coveralls --stdout < coverage/lcov.info > coverage/jsfiles.json; fi
  - if [ -n "$DO_COVERAGE" ]; then coveralls-merge coverage/jsfiles.json coverage/cppfiles.json; fi
  # publish for node-pre-gyp
  - node-pre-gyp package $NPG_ARGS
  - if [ -n "$TRAVIS_TAG" -a $CXX = "g++-4.8" ]; then echo 'put build/stage/lzma-native/* uploads/lzma-native/' |sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -b- -i .travis.id_rsa node-pre-gyp@entless.org; fi
